blogTitle = "Len Smith"
subTitle = "I make software with computers"
blogUrl = "http://ignu.me"
authorName = "Len Smith"
authorBio = "Written by <strong>Len Smith</strong> who lives and works in Seattle. Follow him on <a href='https://twitter.com/ignu'>Twitter</a>, <a href='https://github.com/ignu'>Github</a> or listen to him on <a href='https://turing.cool'>Turing-Incomplete</a>"
linkPrefix = "/ignu"
# gaCode = "UA-0000000-0"
# disqusShortname = "yoursite"
# kommentsCode = "00000000-0000-0000-0000-000000000000"
